INSERT INTO states(id, name, country_id) VALUES('1', 'Aguascalientes', '1');
INSERT INTO states(id, name, country_id) VALUES('2', 'Baja California', '1');
INSERT INTO states(id, name, country_id) VALUES('3', 'Baja California Sur', '1');
INSERT INTO states(id, name, country_id) VALUES('4', 'Campeche', '1');
INSERT INTO states(id, name, country_id) VALUES('5', 'Coahuila de Zaragoza', '1');
INSERT INTO states(id, name, country_id) VALUES('6', 'Colima', '1');
INSERT INTO states(id, name, country_id) VALUES('7', 'Chiapas', '1');
INSERT INTO states(id, name, country_id) VALUES('8', 'Chihuahua', '1');
INSERT INTO states(id, name, country_id) VALUES('9', 'Ciudad de México', '1');
INSERT INTO states(id, name, country_id) VALUES('10', 'Durango', '1');
INSERT INTO states(id, name, country_id) VALUES('11', 'Guanajuato', '1');
INSERT INTO states(id, name, country_id) VALUES('12', 'Guerrero', '1');
INSERT INTO states(id, name, country_id) VALUES('13', 'Hidalgo', '1');
INSERT INTO states(id, name, country_id) VALUES('14', 'Jalisco', '1');
INSERT INTO states(id, name, country_id) VALUES('15', 'México', '1');
INSERT INTO states(id, name, country_id) VALUES('16', 'Michoacán de Ocampo', '1');
INSERT INTO states(id, name, country_id) VALUES('17', 'Morelos', '1');
INSERT INTO states(id, name, country_id) VALUES('18', 'Nayarit', '1');
INSERT INTO states(id, name, country_id) VALUES('19', 'Nuevo León', '1');
INSERT INTO states(id, name, country_id) VALUES('20', 'Oaxaca', '1');
INSERT INTO states(id, name, country_id) VALUES('21', 'Puebla', '1');
INSERT INTO states(id, name, country_id) VALUES('22', 'Querétaro', '1');
INSERT INTO states(id, name, country_id) VALUES('23', 'Quintana Roo', '1');
INSERT INTO states(id, name, country_id) VALUES('24', 'San Luis Potosí', '1');
INSERT INTO states(id, name, country_id) VALUES('25', 'Sinaloa', '1');
INSERT INTO states(id, name, country_id) VALUES('26', 'Sonora', '1');
INSERT INTO states(id, name, country_id) VALUES('27', 'Tabasco', '1');
INSERT INTO states(id, name, country_id) VALUES('28', 'Tamaulipas', '1');
INSERT INTO states(id, name, country_id) VALUES('29', 'Tlaxcala', '1');
INSERT INTO states(id, name, country_id) VALUES('30', 'Veracruz de Ignacio de la Llave', '1');
INSERT INTO states(id, name, country_id) VALUES('31', 'Yucatán', '1');
INSERT INTO states(id, name, country_id) VALUES('32', 'Zacatecas', '1');
