INSERT INTO states(id, name) VALUES('1', 'Aguascalientes');
INSERT INTO states(id, name) VALUES('2', 'Baja California');
INSERT INTO states(id, name) VALUES('3', 'Baja California Sur');
INSERT INTO states(id, name) VALUES('4', 'Campeche');
INSERT INTO states(id, name) VALUES('5', 'Coahuila de Zaragoza');
INSERT INTO states(id, name) VALUES('6', 'Colima');
INSERT INTO states(id, name) VALUES('7', 'Chiapas');
INSERT INTO states(id, name) VALUES('8', 'Chihuahua');
INSERT INTO states(id, name) VALUES('9', 'Ciudad de México');
INSERT INTO states(id, name) VALUES('10', 'Durango');
INSERT INTO states(id, name) VALUES('11', 'Guanajuato');
INSERT INTO states(id, name) VALUES('12', 'Guerrero');
INSERT INTO states(id, name) VALUES('13', 'Hidalgo');
INSERT INTO states(id, name) VALUES('14', 'Jalisco');
INSERT INTO states(id, name) VALUES('15', 'México');
INSERT INTO states(id, name) VALUES('16', 'Michoacán de Ocampo');
INSERT INTO states(id, name) VALUES('17', 'Morelos');
INSERT INTO states(id, name) VALUES('18', 'Nayarit');
INSERT INTO states(id, name) VALUES('19', 'Nuevo León');
INSERT INTO states(id, name) VALUES('20', 'Oaxaca');
INSERT INTO states(id, name) VALUES('21', 'Puebla');
INSERT INTO states(id, name) VALUES('22', 'Querétaro');
INSERT INTO states(id, name) VALUES('23', 'Quintana Roo');
INSERT INTO states(id, name) VALUES('24', 'San Luis Potosí');
INSERT INTO states(id, name) VALUES('25', 'Sinaloa');
INSERT INTO states(id, name) VALUES('26', 'Sonora');
INSERT INTO states(id, name) VALUES('27', 'Tabasco');
INSERT INTO states(id, name) VALUES('28', 'Tamaulipas');
INSERT INTO states(id, name) VALUES('29', 'Tlaxcala');
INSERT INTO states(id, name) VALUES('30', 'Veracruz de Ignacio de la Llave');
INSERT INTO states(id, name) VALUES('31', 'Yucatán');
INSERT INTO states(id, name) VALUES('32', 'Zacatecas');
